version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - '6379:6379'
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '8080:8080'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
